# Generated by Django 3.2 on 2022-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='body',
            field=models.TextField(default='Add your review here'),
        ),
    ]
